### ISSUE TITLE
The code does not stop at tMax in restart mode

### ISSUE THREAD

**Issue by Bai-Zhan** [cosmolattice/cosmolattice#5]
Line 127 of cosmolattice.cpp is:

```for (int i = 0 ; i < static_cast<int>(runParams.tMax / model.dt); ++i)```

However, this loop does not stop at ```runParams.tMax```, as one would expect.
It will stop at t+tMax, where t is the starting time of this run.

**Comment by cosmolatticeacc** [comment]
Thanks for spotting this. It was a bad idea last minute change before the release... I created a new branch "bug_restart_tMax" with a fix, could you download it and confirm that it indeed works now? I will then merge it in the main branch.

**Comment by Bai-Zhan** [comment]
The loop command now is:

```for (int i = 0 ; t < runParams.tMax +runParams.dt / 2.0; ++i) ```

At t==tMax, the code will still enter the loop, and evolve for a timestep,
so the output will be a snapshot at time tMax+dt.

I think this loop command should be:
```for (int i = 0 ; t < runParams.tMax - runParams.dt / 2.0; ++i) ```
In this way, the output snapshot will be exactly at time tMax,
which I would expect from intuition.


Best Regards

Zhan Bai
Institute of Theoretical Physics,
Beijing, China

________________________________
发件人: cosmolattice ***@***.***>
发送时间: 2022年5月11日 2:30
收件人: cosmolattice/cosmolattice ***@***.***>
抄送: Bai-Zhan ***@***.***>; Author ***@***.***>
主题: Re: [cosmolattice/cosmolattice] The code does not stop at tMax in restart mode (Issue #5)


Thanks for spotting this. It was a bad idea last minute change before the release... I created a new branch "bug_restart_tMax" with a fix, could you download it and confirm that it indeed works now? I will then merge it in the main branch.

―

**Comment by cosmolatticeacc** [comment]
Yes of course! I changed that and am merging it into the master. Thanks for reporting the bug!
